# fly.toml app configuration file generated for bender-chat on 2023-05-11T11:06:45+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bender-chat"
primary_region = "mia"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
